### PR TITLE
Refactor/include fix

### LINKED ISSUE #181: Refactor: include the nescessary field for enable/disable related operations

### PR DESCRIPTION
**Pull request by vzart**

### CODE REVIEW

File: src/Application/Folders/Commands/DisableFolder.cs [hunk 1]
```diff
@@ -40,6 +40,7 @@ public CommandHandler(IApplicationDbContext context, IMapper mapper)
         public async Task<FolderDto> Handle(Command request, CancellationToken cancellationToken)
         {
             var folder = await _context.Folders
+                .Include(x => x.Locker)
```
Comment (ChienNQuang) [inline src/Application/Folders/Commands/DisableFolder.cs:43]: I think it'd be great if you also include room

File: src/Application/Folders/Commands/EnableFolder.cs [hunk 2]
```diff
@@ -28,6 +28,7 @@ public CommandHandler(IApplicationDbContext context, IMapper mapper)
         public async Task<FolderDto> Handle(Command request, CancellationToken cancellationToken)
         {
             var folder = await _context.Folders
+                .Include(x => x.Locker)
```
Comment (ChienNQuang) [inline src/Application/Folders/Commands/EnableFolder.cs:31]: same argument

File: src/Application/Lockers/Commands/DisableLocker.cs [hunk 3]
```diff
@@ -40,6 +40,7 @@ public CommandHandler(IApplicationDbContext context, IMapper mapper)
         public async Task<LockerDto> Handle(Command request, CancellationToken cancellationToken)
         {
             var locker = await _context.Lockers
+                .Include(x => x.Room)
```
Comment (ChienNQuang) [inline src/Application/Lockers/Commands/DisableLocker.cs:43]: and department also

**Review by ChienNQuang — CHANGES_REQUESTED** [review]
get user by id needs department included also

**Review by ChienNQuang — APPROVED** [review]
ok
